### ISSUE TITLE
marks flicker when data renewed

### ISSUE THREAD

**Issue by crowcc** [marcosun/react-amap-2drender#1]
Each times I pass new props to the Marker component, all markers will flicker. Is there anyway to prevent it?

**Comment by marcosun** [comment]
Every time 2drender need an update, whatever it was after dragging map or updating marker positions, canvas was cleared before performing an asynchronous refresh just like what it did at initialisation.

From v1.2.0, when 2drender requires a refresh, canvas is updated asynchronously at background, while keeping foreground canvas unchanged. As soon as background canvas has completed rendering, 2drender updates foreground canvas instantly.
